### ISSUE TITLE
Regression in 1.9.2-dev:    toLowerCase is not a function

### ISSUE THREAD

**Issue by tom-berend** [jsxgraph/jsxgraph#683]
Works in 1.9.1

```
    <div id="jxgbox" class="jxgbox" style="width:500px; height:200px;"></div>
    <script type="text/javascript">
        let B = JXG.JSXGraph.initBoard('jxgbox')
        let p1 = B.create('point',[-3, -4]);
        let p2 = B.create('point',[3, -1]);
        let p3 = B.create('point',[-2, 0]);
        let par = B.create('parallelogram',[p1, p2, p3])
    </script>

```

**Comment by alfredwassermann** [comment]
Thanks a lot for pointing this out!

Fixed by 310b6c8ed6e27d22c54cf42ce77a55ccc2bc2b19
